### ISSUE TITLE
'kactus parse' fails if a page name has '/' in it

### ISSUE THREAD

**Issue by aparajita** [kactus-io/kactus-cli#5]
If you have a page name that contains '/', `kactus parse` fails, most likely because it's trying to build a path including the name.

**Comment by mathieudutour** [comment]
Hum good catch. Not sure what would be the right solution for this one 🤔

**Comment by aparajita** [comment]
If it were me, for the purposes of constructing a path I would replace `/` (which is called SOLIDUS in Unicode) with a Unicode character that looks like `/` but is likely never to be used. Some possibilities:

* ∕ &nbsp;U+2215 (DIVISION SLASH)
* ⁄ &nbsp;U+2044 (FRACTION SLASH)
* ／&nbsp;U+FF0F (FULLWIDTH SOLIDUS)

**Comment by mathieudutour** [comment]
make sense. Would you transform them back when recreating the sketch file or it's fine?

**Comment by aparajita** [comment]
Definitely reverse the transform. Users will expect layer names to be remain unchanged in the source Sketch file.

**Comment by mathieudutour** [comment]
I tend to agree. so we are just hoping that nobody will use those unicode characters.

**Comment by aparajita** [comment]
Extremely unlikely those would be used, I'll bet 99% of the people don't know they exist, especially fullwidth solidus. You could just as easily use some other obscure character, it doesn't have to look like solidus. In any case it should be documented that whatever the replacement character is should not be used in layer names.

**Comment by mathieudutour** [comment]
actually I'm not using the name of the folder to recreate the sketch file so all good.

Fixed in 0.3.1
